---
- hosts: prod_server_user
  vars_files:
    - vars.yml
    - secrets.yml

  tasks:

    - name: Clear tmp folder
      command: rm -Rf /home/{{ projectUser }}/tmp/*

    - name: Create MongoDb backup
      command: mongodump --out /home/{{ projectUser }}/tmp

    - name: Zip MongoDb backup
      command: tar -cvf /home/{{ projectUser }}/backupdb/{{ ansible_hostname }}--{{ ansible_date_time.date }}--{{ ansible_date_time.time }}--backup.tar.gz /home/{{ projectUser }}/tmp

    # Rsync better for this, but it not working for me with WSL

    - find: paths="/home/{{ projectUser }}/backupdb/" recurse=no patterns="*.tar.gz"
      register: files_to_copy

    - fetch: src={{ item.path }} dest={{ localPathWSLBackUp }} flat=yes
      with_items: "{{ files_to_copy.files }}"

    - name: Get frontend files from git
      git:
        force : yes
        repo: 'https://{{ gitUser }}:{{ bitbucketPassword }}@bitbucket.org/{{ projectName }}/{{ projectNameFrontend }}.git'
        dest: '/home/{{ projectUser }}/{{ projectNameFrontend }}'

    - name: Get backend files from git
      git:
        force : yes
        repo: 'https://{{ gitUser }}:{{ bitbucketPassword }}@bitbucket.org/{{ projectName }}/{{ projectNameBackend }}.git'
        dest: '/home/{{ projectUser }}/{{ projectNameBackend }}'

    - name: Copy config.js for Backend (for security reasons it's not under git)
      become: yes
      copy:
        src: '{{ localPathWSL }}/{{ projectNameBackend }}/dist/config.js'
        dest: '/home/{{ projectUser }}/{{ projectNameBackend }}/dist/'
        owner: '{{ projectUser }}'
        group: nginx
        mode: 0644

    - name: Set environment variables
      shell: "echo 'export NODE_ENV=production && export PRODUCTION_PLATFORM=server && export PROJECT_DOMAIN={{projectDomain}}' >> $HOME/.bashrc && source $HOME/.bashrc"

    - name: Install packages based on package.json for Backend
      npm:
        path: /home/{{ projectUser }}/{{ projectNameBackend }}/

    - name: Install devDependency for Backend
      shell: 'npm install --only=dev'
      args:
        chdir: /home/{{ projectUser }}/{{ projectNameBackend }}/

    - name: Remove all old frontend files
      become: yes
      shell: 'rm -fR {{ productionFrontendPath }}/*'

    - name: Copy frontend dist files for production
      become: yes
      shell: 'cp -R /home/{{ projectUser }}/{{ projectNameFrontend }}/dist/* {{ productionFrontendPath }}'

    - name: Change permission for files, user and group
      become: yes
      shell: 'chown -R {{ projectUser }}:nginx {{ productionFrontendPath }}/* &&
              chmod -R u+x,g+x,o+x {{ productionFrontendPath }}/*'

    - name: Reload nginx
      become: true
      service:
        name: nginx
        state: reloaded

    - name: Restart nginx
      become: true
      service:
        name: nginx
        state: restarted

    - name: Start/Restart backend with PM2
      shell: 'pm2 start app.js -f --name "api" --watch'
      args:
        chdir: /home/{{ projectUser }}/{{ projectNameBackend }}/dist